name: decoder
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  shelf: ^1.4.0
  substrate_metadata:
    path: polkadart/packages/substrate_metadata
  polkadart_scale_codec:
    path: polkadart/packages/polkadart_scale_codec
  compute: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
