name: platform_decoder
description: Enjin Platform Decoder
version: 1.6.0
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  shelf: ^1.4.1
  polkadart: ^0.4.3
  substrate_metadata: ^1.2.0
  polkadart_scale_codec: ^1.2.0
  compute: ^1.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
